---
# Site settings
title: Responsible Drinking Title
brand: Responsible Drinking Brand
subtitle: A Discreet Inquiry and a Modest Proposal
author: Robert C. Binkley
publisher: Vanguard Press
date: 1930
description: > # this means to ignore newlines until "baseurl:"
  Robert C. Binkley, Responsible Drinking: A Discreet Inquiry and a Modest Proposal (New York: Vanguard Press, 1930)
description_latex: > # this means to ignore newlines until "baseurl:"
  Robert C. Binkley, \textit{Responsible Drinking: A Discreet Inquiry and a Modest Proposal} (New York: Vanguard Press, 1930)
baseurl: "/ethertheories.com" # the subpath of your site, e.g. /blog
url: "https://www.wallandbinkley.com"
contentslink: "chapter-contents.html"
editor: Peter Binkley
twitter: "@pabinkley"
license_icon: assets/publicdomain.png
cover_image: &cover_image assets/cover.jpg
license_text: "To the extent possible under law, Peter Binkley has waived all copyright and related or neighboring rights to \"Title of Book\". This work is published from: Canada."
jb_credit_latex: "Generated with jekyll-book ¶ \\href{https://github.com/pbinkley/jekyll-book}{https://github.com/pbinkley/jekyll-book}"
# Info for CC license vcard in _includes/license.html
publisher_url: "https://github.com/fortran-team/ethertheories.com"
country_name: Canada
country_code : CA
dirdownloads: downloads
dircontent: sections
previousrun: _data/previousrun.yml

# Build settings
markdown: Pandoc
mainfont: Times New Roman
monofont: Courier New
mathfont: TeX Gyre Termes Math # This is a clone of Times
fontsize: 14
pandoc:
  extensions:
    - mathjax

# downloads files are generated during the rendering, so we need to 
# ignore them or it will cause an infinite loop of re-rendering
exclude: ['_data/previousrun.yml','downloads','Gemfile*','README.md']

# The navigation.
navigation:
  left:
    links:
#      - title: Home
#        href: /ethertheories.com/
      - title: Chapters
        dropdown: sections
      - title: Downloads
        dropdown: downloads
  right:
    content: searchbox.html

plugins:
  - jekyll-sitemap
  - octopress-debugger
#  - jekyll-lunr-js-search
  - jekyll-pandoc

downloads:
    pdf:
      deps: ["_config.yml","_latex/jekyll-book.latex","_scripts/preprocess_pdf.rb","_scripts/abstract_preprocess.rb",*cover_image]
      command: "ruby _scripts/preprocess_pdf.rb _config.yml sections/*.md | pandoc --pdf-engine=xelatex --template=_latex/jekyll-book.latex -o %{dirDownloads}/%{slug}.pdf"
    epub:
      deps: ["_config.yml","_scripts/preprocess_epub.rb","_scripts/abstract_preprocess.rb",*cover_image]
      command: "ruby _scripts/preprocess_epub.rb _config.yml sections/*.md | pandoc -t epub2 --webtex --epub-cover-image=%{coverImage} -o %{dirDownloads}/%{slug}.epub"
    txt:
      deps: ["_config.yml"]
      command: "cat sections/*.md | pandoc -t plain -o %{dirDownloads}/%{slug}.txt"
    md:
      deps: ["_config.yml"]
      command: "cat sections/*.md | pandoc -o %{dirDownloads}/%{slug}.md"
---
